#!/bin/bash

exec_path=$1
echo ${exec_path}

config_path=$2
echo ${config_path}

ip=$3
echo ${ip}

first_port=$4
last_port=$5

for (( port=${first_port}; port<last_port; port++ ))
do
    echo ${port}
    exec ${exec_path} ${config_path} ${ip} ${port} > daemon-log${ip}:${port}.txt &
    shift
done
